# -*- coding: utf-8 -*-
"""Cyborg_automation_task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iWA5Jx3HXTbdCwBJ0Nz8ZrjRsnML951_
"""

import re

def get_words(fname):
  words=set()
  re_nonalpha=re.compile('[^a-zA-Z ]+')
  with open(fname) as fh:
    for line in fh:
      line=re_nonalpha.sub(' ',line)
      
      for word in line.split():
        words.add(word.lower())
    word_list=list(words)
    word_list.sort()
    return word_list

fname='/content/dictionary.txt'
get_words(fname)

def append_words(string1):
  with open(fname,'a+') as fh:
    fh.seek(0)
    data=fh.read(100)
    if len(data)>0:
      fh.write("\n")
    fh.write(string1)

append_words('astronomy')
get_words(fname)

string2=[]
def search_words(fname,string2):
  words=[]
  re_nonalpha=re.compile('[^a-zA-Z ]+')
  with open(fname) as fh:
    for line in fh:
      line=re_nonalpha.sub(' ',line)
      for word in line.split():
        word=word.lower()
        for i in range(len(string2)):
          if list(string2)[i]==list(word)[i]:
            i=i+1
          else:
            break
        if i==len(string2):
          words.append(word.lower())
        
    return words



string2='as'
search_words(fname,string2)

fname='/content/dictionary.txt'
def correct_spellings(textToSearch,textToReplace):
  #read input file
  fin = open(fname, "rt")
  #read file contents to string
  data = fin.read().lower()
  
  #replace all occurrences of the required string
  data = data.replace(textToSearch,textToReplace.lower())
  #close the input file
  fin.close()
  #open the input file in write mode
  fin = open(fname, "wt")
  #overrite the input file with the resulting data
  fin.write(data)
  #close the file
  fin.close()

correct_spellings('awful','aweful')

fname='/content/dictionary.txt'
get_words(fname)

def delete_words(word):
  f = open(fname,'r')
  lst = []
  for line in f:
    if word in line:
      line = line.replace(word,'')
    lst.append(line)
  f.close()
  f = open(fname,'w')
  for line in lst:
    f.write(line)
  f.close()

delete_words('aroma')
get_words(fname)